### ISSUE TITLE
Docker版本参考 (`docker-compose.yml`)

### ISSUE THREAD

**Issue by Patrick-Ze** [pmkol/easymosdns#40]
苦于没找到docker版本，摸索着写了个 docker-compose.yml 。#22 里提到很简单，我写完回过头来看确实很简单，属实会者不难，问题是不会。

放在这里供有需要的人参考。

1. 下载此仓库并解压
```sh
wget https://mirror.apad.pro/dns/easymosdns.tar.gz
tar xzf easymosdns.tar.gz
```

2. 创建`docker-compose.yml`，内容如下
```yaml
version: '3'
services:
  mosdns:
    image: irinesistiana/mosdns:v4.5.3
    container_name: mosdns
    restart: unless-stopped
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./easymosdns:/etc/mosdns
```

3. 基于`docker-compose.yml`配置文件启动docker container: `docker compose up -d`

#22 #38
